generic-service:
  nameOverride: hmpps-dpr-tools-ui
  productId: "UNASSIGNED" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-dpr-tools-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    tlsSecretName: hmpps-dpr-tools-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
    INGRESS_URL: dpr-tools-ui-dev.hmpps.service.justice.gov.uk
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_TOOLS_USER

  namespace_secrets:
    hmpps-dpr-tools-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    hmpps-dpr-tools-ui-ec-cluster-output:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    ui-session-secret:
      SESSION_SECRET: "session_secret"
    hmpps-auth:
      API_CLIENT_ID: "api_client_id"
      API_CLIENT_SECRET: "api_client_secret"
      SYSTEM_CLIENT_ID: "system_client_id"
      SYSTEM_CLIENT_SECRET: "system_client_secret"

  # Group name source: https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml
  allowlist:
    consultant-ip: 217.155.59.19
    groups:
      - circleci
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: hmpps-dpr-tools-ui
